### ISSUE TITLE
Assignment 1 Sven

### ISSUE THREAD

**Issue by sweerdenburg1** [EstherPlomp/TNW-RDM-101#12]
### Introduction

Hi, I'm Sven and I am a PhD student at the catalysis engineering section in the chemical engineering department.

### Reflections on the importance of RDM videos

I recognize how important it is to write down all your steps to make your results reproducible. While I was a student, I sometimes forgot to write down the details of my experiment in my lab journal. If the next time I'd be in the lab were after a weekend or holiday, I'd forgotten entirely what I've done, which resulted in me repeating the experiment. Now it's a routine to make sure I log everything before I go home.

### What would you like to learn during this course? 

I am curious how to use GitHub to backup my scripts and share my code with others. I am also interested in some best practices for storing my data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1: (Made with [Begüm)](https://github.com/EstherPlomp/TNW-RDM-101/issues/17) [Download](https://surfdrive.surf.nl/files/index.php/s/kReGN8f28WmCzjN)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @begum94 and @SvenWeerdenburgCE: Well done on assignment 1! I love the added lab safety sheets - indeed important to also manage alongside the generated data. You don't mention estimations of the size of the data that you collect. With the data that you mention I think the 500 GB that SURFdrive provides should be sufficient. Should you need more, there's also OneDrive and the Project Drive. 

I also noticed that there are no red flags - that makes life a lot easier!

**Comment by Azinkarimzad** [comment]
"I like your step-by-step data storage strategy! The digital lab journal and lab safety sheets also look promising to me!"

**Comment by MiriamCammaert** [comment]
Hi Sven and Begum, I like that you separated the raw data measurements from the processed data measurements as data output. Also, nice that you included storage of the lab safety sheets. It looks like a good Data FlowMap format!

**Comment by sweerdenburg1** [comment]
This is the README.txt file I made for my PhD project

[README.txt.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/10966104/README.txt.txt)

**Comment by sweerdenburg1** [comment]
Here is the data flow map for the second assignment.
[RDM101_Assignment2_Week2_DataFlowMap_Sven.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/10966781/RDM101_Assignment2_Week2_DataFlowMap_Sven.pptx)

**Comment by EstherPlomp** [comment]
Well done on assignment 3 - everything looks very clear! I just have a couple of questions/suggestions below:

A more general question on organisation: 
- How will you connect the information from the lab journal to your experiment? By date? Will you generate an identifier? How would this look like? (If this is the link described in the metadata theme, note that links can also break - even if they break how do you ensure correct identification?)

On documentation: 
- Will your scripts also contain comments with metadata? The required libraries?

On file formats: 
- odt is an open format! docx is actually proprietary because you'll need a Microsoft Office license. Because most universities have these licenses it appears to be open and it certainly is commonly used. When you share these documents it can be helpful to use both an open and commonly used format: the commonly used/user-friendly format may be easier to reuse in this sense, but the open format helps to keep the information available and preserved. 

I hope this makes sense - if not, please comment below!

**Comment by sweerdenburg1** [comment]
> Well done on assignment 3 - everything looks very clear! I just have a couple of questions/suggestions below:
> 
> A more general question on organisation:
> 
> * How will you connect the information from the lab journal to your experiment? By date? Will you generate an identifier? How would this look like? (If this is the link described in the metadata theme, note that links can also break - even if they break how do you ensure correct identification?)
> 
> On documentation:
> 
> * Will your scripts also contain comments with metadata? The required libraries?
> 
> On file formats:
> 
> * odt is an open format! docx is actually proprietary because you'll need a Microsoft Office license. Because most universities have these licenses it appears to be open and it certainly is commonly used. When you share these documents it can be helpful to use both an open and commonly used format: the commonly used/user-friendly format may be easier to reuse in this sense, but the open format helps to keep the information available and preserved.
> 
> I hope this makes sense - if not, please comment below!

Thank you for your feedback, @EstherPlomp! 

Regarding the question on organisation, I create an identifier for each sample and measurement (e.g. SW-3_1, SW-3_2, etc.). In my labjournal I use the identifier to refer to my samples and measurements, and my measurement data always has the identifier in its name.

My scripts will contain comments to make the code understandable. The required libraries and library versions will be stored in a README.txt file in the same directory as the script.

Good to know, I did not know .odt is an open format. I have used a template file that is on my group's SurfDrive to make my labjournal. It makes sense to me now why the .odt format was chosen instead of a .docx file format.

**Comment by sweerdenburg1** [comment]
This is the data management plan that I made in November 2022.

[Data Management Plan.pdf](https://github.com/EstherPlomp/TNW-RDM-101/files/11075922/Data.Management.Plan.pdf)

**Comment by sweerdenburg1** [comment]
[Assignment 5.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/11076273/Assignment.5.pptx)
