### ISSUE TITLE
Assignment 1 [Chaofan Chen]

### ISSUE THREAD

**Issue by cfchen98** [EstherPlomp/TNW-RDM-101#13]
### Introduction

Hi, I am Chaofan Chen, a second year phD student from department of radiation science and technology. My research topic is about electrochemical energy storage.

### Reflections on the importance of RDM videos

The reproducibility is vital in every step in research works, from the start of a project, then data analysis and paper writing and review process. Transparent and proper repository of research data would help us trace back the overall research process and build up our contribution.
### What would you like to learn during this course? 

How to properly manage the research data. Try to make my research work more reproducible.
### Link of Assignment 2:
https://surfdrive.surf.nl/files/index.php/s/cAATwrifmz611p0
### Link of Readme template:
https://surfdrive.surf.nl/files/index.php/s/u4qAGX49tt1GbUl
### Link of Assignment 3:
https://surfdrive.surf.nl/files/index.php/s/2XGk1soitBZFXzD
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @cfchen98! Well done on assignment 2! You don't have any 'red flags' to deal with I see - that should make life easier! In the upcoming week it would be good to think about whether it makes sense to share the raw electrochemical test data if it can only be opened with certain software.

**Comment by MBeatrizDiniz** [comment]
Hello @cfchen98, I think the data flow is really clear! Maybe with your electrochemical data test data, you can have a readme file explaining how to open the files in the software you mentioned.

**Comment by maverheijen** [comment]
Hi! Data Flow Map looks really clear. I think it's nice how you already have a flow from data collection/creation to the analysis! I would think maybe that reusing the material characterization data of your collaborator might be considered a 'red flag', as this requires some communication on data handling there.

**Comment by EstherPlomp** [comment]
Well done on **assignment 3** - it looks clear! 

On documentation: 
- I miss a bit of detail on what metadata you'll collect. What variables, parameters or information will you need from your data collection process? (for example, if you're working in Excel sheets: what column headers do these sheets have and what types of information are you collecting per experiment?)
- When you receive data from collaborators, do you receive all the information you need to interpret the data? Do you find their readme files helpful? Can you reuse this as a base for your own readme files? 

On file formats: 
- Good to see that even when the software is perhaps closed/proprietary, (some of) the outputs can be shared in open formats!

On data publication: 
- I'm wondering why you put a red flag 'Access' in this slide? Do you have any concerns about the sharing process or do you expect any difficulties? As you don't have any other red flags - I hope this process is relatively straight forward for your project.

**Comment by EstherPlomp** [comment]
That makes more sense now - thanks for clarifying!

**Comment by EstherPlomp** [comment]
Hi @cfchen98! 

Thanks for sharing your READme file! Was it difficult to set this up? If you have any feedback on how we can improve this part of the course, please let me know!

For the contact details you can also add any collaborators involved, so most likely your supervisor - and possibly more! You can also set up an ORCID which you can share here. an ORCID is similar like the identifier to the publication, it provides a way to easily identify you as a person and associate your research outputs with you. You can [set up your own ORCID](https://orcid.org/register) very easily (and use it for some scholarly platforms such as Zenodo/publishing platforms). You can have a look at [Xuehang's ORCID](https://orcid.org/0000-0002-8984-6162) to see what it looks like when there is information in the profile. 

For the license information you could fill out the [preferred option you choose in the discussion thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9#discussioncomment-5300912).

**Comment by cfchen98** [comment]
Dear Esther,

I create my ORCID account today accordingly.
I have learned a lot from this course. Thanks for your effort!

Best regards,
Chaofan
