### ISSUE TITLE
Assignment 1 Brenda Juarez

### ISSUE THREAD

**Issue by bejuarez96** [EstherPlomp/TNW-RDM-101#18]
### Introduction
Hi all, my name is Brenda Juarez Garza, I am from Mexico and I am currently starting my PhD at TU Delft in the Faculty of Applied Sciences. My project is about the production of red blood cells using stem cells to use them as a treatment for congenital anemias.

### Reflections on the importance of RDM videos
I consider that Research Data Management is very important to learn, especially when you start a research project, to avoid losing your data and continue your research without problems. Being able to share your data with other collaborators to get some feedback or input is crucial to improve your research and getting other perspectives that can be helpful. Luckily, I haven't lost any research data in any of my projects. I always try to store my data in the cloud just to be safe, because you never know what could happen. However, I believe that this course will give me more insights into better research data management strategies.

### What would you like to learn during this course? 
I would like to learn strategies to manage my research data and how to make accessible my data to other researchers or reviewers to get some input or feedback.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1, Link: https://surfdrive.surf.nl/files/index.php/s/Yc0BzpN8IOHzIW3
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 : https://surfdrive.surf.nl/files/index.php/s/UxKGsyJZf06OVz6
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**): https://surfdrive.surf.nl/files/index.php/s/RVStI8vYf9TYdxR

**Comment by EstherPlomp** [comment]
Well done on assignment 2 @bejuarez96! With "First, the data will be stored in my TU Delft laptop.." do you also mean OneDrive there?

**Comment by bejuarez96** [comment]
> Well done on assignment 2 @bejuarez96! With "First, the data will be stored in my TU Delft laptop.." do you also mean OneDrive there?

Yes, I meant in the hard disk of the computer and on the One Drive :)

**Comment by EstherPlomp** [comment]
Alright, thanks!

**Comment by bejuarez96** [comment]
Read me file: https://surfdrive.surf.nl/files/index.php/s/gcIOOwP3iaAXwVU

**Comment by EstherPlomp** [comment]
Well done on assignment 3! It looks super clear so I again have very little feedback 👍 

On documentation: 
- Great idea to see how Sanquin is handling data documentation!
- Do you have all the information you need to set up a data dictionary?

**Comment by bejuarez96** [comment]
Thanks for your feedback @EstherPlomp ! I think that once I start creating my documents with my experimental set-up and results, I would complete in a separate document my data dictionary.

**Comment by EstherPlomp** [comment]
Hi @bejuarez96! 

Thanks for sharing your READme file: great start with all of the involved researchers and contact details. I see you're not listing any ORCIDs, so I just wanted to highlight that this is a type of identifier for researchers. Similar like the identifier to the publication, it provides a way to easily identify you as a person and associate your research outputs with you. You can [set up your own ORCID](https://orcid.org/register) very easily (and use it for some scholarly platforms such as Zenodo/publishing platforms). As an example, you can have a look at Marieke's ID: [0000-0001-5203-4649](https://orcid.org/0000-0001-5203-4649).

I guess this assignment was a bit difficult to do when you don't have a finished dataset. If you have any feedback on how we could improve this part of the course, please let me know!
