### ISSUE TITLE
Assignment 1 Ramon van Valderen

### ISSUE THREAD

**Issue by RamonvanValderen** [EstherPlomp/TNW-RDM-101#19]
### Introduction
Hi, my name is Ramon and I'm a PhD student at the Bioprocess Engineering section focused on computational analysis of stem cell production in bioreactors. Specifically, I'm using Computational Fluid Dynamics (CFD) simulations and kinetic models of cells to characterize the cultivation conditions from the cellular perspective, with the ultimate aim to optimize the operational parameters and define scale-up criteria. In my free time I like to sport and play the piano.

### Reflections on the importance of RDM videos
In my personal experience I've always made sure that my (personal) data was always backed up somewhere to prevent such "horror stories" of a stolen laptop where multiple years of research is suddenly lost. Incorporating this good practice during my PhD project was therefore one of the first things I did. However, I learned that RDM is much more than just having your data backed-up, as it also essential for making your research reproducible, which in turn would help me with avoiding science disasters, writing papers, communicating with reviewers and more! I am therefore eager to think of new RDM practices and habits that would help me make my research more reproducible. 

### What would you like to learn during this course? 
I would like to hear from others how they implemented their RDMP into their daily workflow. Of course, everyone has their own specific type of research with their specific type of data and data analysis, which means that everyone, including me, has to figure out a workflow that works best for them. Nevertheless, discussing this topic with peers might help get inspiration on how to improve your daily RDM.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**):
Link to Data Flow Map 1: https://tud365-my.sharepoint.com/:p:/g/personal/rdvanvalderen_tudelft_nl/EQpFejp3j4tCkARIsjgotAoBUW6ot8ITW-_iHCY8IVPQ3g?e=aqQdOg
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**):
https://tud365-my.sharepoint.com/:p:/g/personal/rdvanvalderen_tudelft_nl/EQYaCA15ubtAnQ66qZIObGQBYCb-iJtkTp3uSPKrLUJwCA?e=4OTYXf
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by RamonvanValderen** [comment]
[RamonvanValderen_TRACER-CFD_Readme.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/10839046/RamonvanValderen_TRACER-CFD_Readme.txt)

**Comment by EstherPlomp** [comment]
Hi @RamonvanValderen! Assignment 1 is looking great - I don't have anything to add! It can't hurt to have another backup of the files somewhere indeed 😸

**Comment by EstherPlomp** [comment]
Absolutely fantastic job on Assignment 3. I have no feedback, other than a question which relates to the question above on confidential data: 

On the theme Access: 
- You mention that the data will not be shared - is that due to their size or the nature of the confidential data?

And I hope you had a lovely holiday!

**Comment by RamonvanValderen** [comment]
Thx for the feedback all! The main reason for not sharing, let's say, the RAW data and semi-processed data, is purely due to the large file sizes (multiple GBs).
