### ISSUE TITLE
Assignment 1 Tamara Jankovic

### ISSUE THREAD

**Issue by TamaraJankovic03** [EstherPlomp/TNW-RDM-101#20]
### Introduction
Hi all, my name is Tamara Jankovic and I am currently doing PhD at TU Delft at the Faculty of Applied Sciences.

### Reflections on the importance of RDM videos
I think that Research Data Management is a really important skill to learn and apply from the beginning of the project, to avoid some serious problems in the future. Saving your data properly makes your work easier. Additionally, if your colleagues have clear insight into your data, you can get some very valuable feedback.

### What would you like to learn during this course? 
I would like to learn techniques for efficient storing and updating of my data. I believe that this course is a perfect opportunity to achieve this.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [x] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by TamaraJankovic03** [comment]
https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/[RDM101_Assignment1_Week1_DataFlowMap_TamaraJankovic.pptx](https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/RDM101_Assignment1_Week1_DataFlowMap_TamaraJankovic.pptx?d=wf5209e50927044aa95f951d00ab98f90&csf=1&web=1&e=plqpNY)?d=wf5209e50927044aa95f951d00ab98f90&csf=1&web=1&e=plqpNY

**Comment by TamaraJankovic03** [comment]
https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/[RDM101_Assignment1_Week1_DataFlowMap_TamaraJankovic.pptx](https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/RDM101_Assignment1_Week1_DataFlowMap_TamaraJankovic.pptx?d=wf5209e50927044aa95f951d00ab98f90&csf=1&web=1&e=plqpNY)?d=wf5209e50927044aa95f951d00ab98f90&csf=1&web=1&e=plqpNY

**Comment by TamaraJankovic03** [comment]
Here is a link to my Data Flow Map: https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/RDM101_Assignment1_Week1_DataFlowMap_TamaraJankovic.pptx?d=wf5209e50927044aa95f951d00ab98f90&csf=1&web=1&e=plqpNY

**Comment by EstherPlomp** [comment]
Well done on assignment 2 @TamaraJankovic03! 

- Well done for flagging the usage rights when you're collaborating with others
- Do you already have an idea about the file formats of the experimental results? If not, you can focus on the simulation/software files for assignment 3, where file formats have their own theme of reflection. 
- And you have a thorough back-up strategy - impressive!

**Comment by TamaraJankovic03** [comment]
@EstherPlomp thank you for your comment! For each part of the project, I will work either with the experimental results from other colleagues from the group (file formats will probably differ from case to case) or with the data from the literature. So, for the Assignment 3 I will focus on the simulation files and the files with analysis of simulations results.

**Comment by MBeatrizDiniz** [comment]
Hello @TamaraJankovic03, I don't have access to the PowerPoint file.

**Comment by TamaraJankovic03** [comment]
Here is the link to my readme file: https://tud365-my.sharepoint.com/:t:/r/personal/tjankovic_tudelft_nl/Documents/Readme_File_Tamara_Jankovic.txt?csf=1&web=1&e=G3ii5v

**Comment by TamaraJankovic03** [comment]
Hi @MBeatrizDiniz I really don't know what the problem is. When others tried to access my PowerPoint file I got emails with requests, but I didn't get any notification that you tried to access the file.

**Comment by TamaraJankovic03** [comment]
Here is the link to my Data Flow Map 2 (Assignment 3): https://tud365-my.sharepoint.com/:p:/r/personal/tjankovic_tudelft_nl/Documents/RDM101_Assignment2_Week2_DataFlowMap_Tamara_Jankovic.pptx?d=w2f4f1558202343c7aeb3a11b68964d7e&csf=1&web=1&e=BsmuXO

**Comment by MBeatrizDiniz** [comment]
Hello @TamaraJankovic03, you have a very detailed and thorough data flow map! I think one of the main challenges that you will have with your data will be organizing all the sources you are getting data from (other colleagues and literature).

**Comment by maverheijen** [comment]
I have requested feedback to your first Data Flow Map @TamaraJankovic03 ! Will give feedback later.. :)

**Comment by EstherPlomp** [comment]
Many thanks for updating the access rights for Assignment 3, and well done!

On Data organisation: 
-	You mention that you’ll use version numbers, and maybe also the date, to keep track of different versions: Why not both?

On metadata: 
-	Regarding the data of your collaborators: will they provide you with the text files or is this something you need to set up yourself? How do your colleagues describe the data/results?
-	You mention that there are different process sequences? What are these differences? What are the variables/parameters used for these different sequences?
-	What will be the criteria for the best option? Will this vary and if so - how will you adjust these criteria? 

On file formats:
-	Note that Microsoft Excel is not an open format (you need a Microsoft office license)– although it is commonly used. It can be helpful when you publicly share data to have both the Excel files and a conversion to a more open format, such as .csv. This depends on how much formatting exists in your Excel file, such as the graphs that you mention: if too much information is lost it may not be helpful.

On Access: 
-	I think for the Aspen Plus files you’re indicating that these can be open? It looks like part of your answer to Q3 is missing.

**Comment by TamaraJankovic03** [comment]
Dear @EstherPlomp thank you very much for your feedback! :)
Regarding your comments:
- I absolutely agree with you! It can be useful to use both the version numbers and the date.
- I really do not know what the format of the starting data will be for every case. I can give more specific answers for the first two parts of the project, that I have already been working on. For the first part of the project, I have been working with experimental data that was provided to me in an Excel file and I had to write explanations myself. For the second part of the project, I used literature data and also had to write myself the way of processing these data.
- Differences in simulation versions will vary from one project to another. Therefore, I will have to write a separate explanation for every project.
- The criterion for the best option is quite similar for every project: process costs, energy requirements and sustainability metrics will be considered. The best process option is the one that has the lowest costs, energy requirements and values of sustainability metrics.
- Thank you for your advice. However, I have a lot of formatting in my Excel files and I think that a lot will be lost if I convert them to another format.
- My supervisors don't want to share all Aspen Plus files because they've had bad experiences with it in the past (other people tried to use their results and publish them as their own).

**Comment by EstherPlomp** [comment]
Thanks for sharing your READme file @TamaraJankovic03, and well done! It looks very clear and organised. 

Two tiny comments:
- Very nice to see that you already have an ORCID!
- On lines 80-82 you already indicated that it is a single dataset, so you could also delete these lines because they don't provide additional information 

Regarding your previous reaction: 
- If there is a lot of formatting in the Excel files I would then indeed not convert them, because then you'll use the reusability along the way.
- Thanks also for your elaboration about the Aspen files, and sorry to hear that your supervisors had bad experiences with this. That makes it understandable!
