### ISSUE TITLE
Assignment 1 Bert Van Herck

### ISSUE THREAD

**Issue by bertvanherck** [EstherPlomp/TNW-RDM-101#30]
### Introduction
I am Bert, and I am a PhD student in the groups of Cees Dekker and Gijsje Koenderink working with microfluidics to establish a synthetic cell cycle.

### Reflections on the importance of RDM videos
There are multiple reasons to spend time on RDM. 
During my master thesis my hard drive crashed. Fortunately, I saved all data online.   

### What would you like to learn during this course? 
Just get a better understaning of how RDM works, and get tips and tricks to improve my RDM skills. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/7)'
- [x] Assignment 2: Data Flow Map 1 (share a link in this issue before **7 March 13:00**)
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/9)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/10)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Assignment 3: Data Flow Map 2 (share a link in this issue before **14 March 13:00**)
- [x] Assignment 4: Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/11)' if you have any questions (optional)
- [ ] Assignment 5: Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by bertvanherck** [comment]
Data flow map 1:

https://surfdrive.surf.nl/files/index.php/s/V6oCUBFIsApnoiJ

**Comment by RamonvanValderen** [comment]
Hi Bert, data flow map is looking good! I had just one question: Based on your data flow map I presume you'll be performing experiments with microscopes. So I was wondering, is there any (meta-)data you need to store regarding your experiments? (such as what you took the image of and experimental conditions, or microscope settings such as the magnification)

**Comment by EstherPlomp** [comment]
Well done @bertvanherck on assignment 2! 
- following up from @RamonvanValderen's question, are you familiar with [IDR](https://idr.openmicroscopy.org/)?

And a note on the use of group drives: these are generally not recommended for the storage of research data by ICT. The [Project Drive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#project-drive) is the recommended solution for research data.

**Comment by bertvanherck** [comment]
Thank you all for the comments.

Regarding the metadata: it depends upon the used microscope. Some include the desired metadata in the .LIF file, whereas other microscopes create an additional file. I added this to my slides.

I was not familiar with IDR. It looks like a great initiative. It seems that it is only used for cells and (living) tissues. Can it also be used for other microscopy purposes (such as microfluidics, liposomes, ...)?

**Comment by bertvanherck** [comment]
Data flow map 2: https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/RDM&fileid=12685096974

**Comment by EstherPlomp** [comment]
Thanks for responding and updating assignment 2! 

For assignment 3: have you shared the correct file? I only see the backup/storage theme, and assignment 3 also contains slides on metadata, organisation, file format and data access.

Regarding your question about IDR: I thought so, but the platform indeed seems to suggest that it is just cells and living tissues. I sent them an email and will let you know what they say!

**Comment by EstherPlomp** [comment]
Hi @bertvanherck, 

I got a response back from IDR: "IDR aims to hold 'reference image datasets’ as defined at [https://idr.openmicroscopy.org/about/submission.html](https://urldefense.com/v3/__https:/idr.openmicroscopy.org/about/submission.html).  IDR also works with the BioImage Archive ([https://www.ebi.ac.uk/bioimage-archive/](https:/www.ebi.ac.uk/bioimage-archive) to provide public archiving of bioimaging data.

I think what they mean is that if it is bigger than a publication your data is welcome at IDR, and if it is publication based BioImage Archive may be a better solution. 

I hope that helps!

**Comment by bertvanherck** [comment]
Hi Esther,

Sorry for sharing the wrong file. Here is the correct one:

[RDM101_Assignment3.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/11049944/RDM101_Assignment3.pptx)

Regarding IDR: I don't think it will be necessary for my data. However, if the project changes in the coming months/years, it is definitely worth considering to use this platform.

**Comment by EstherPlomp** [comment]
No worries! Your data flow map looks fantastic! I don't have a lot of feedback: 

On documentation:
- I assume you mean eLABjournal? (we have [TU Delft licences](https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook) which you're probably already using but I wanted to link that just in case)

On publication: 
- I see you wrote 'in supplement'. Supplementary files are not following the FAIR principles because they do not get assigned their own persistent identifier (such as a DOI). Nowadays the files that can be shared in supplements are a bit better than just pdfs - but ideally a data repository is still used for this type of information. It will have its own DOI, more visibility and can gather additional citations. Another plus is that you generally are able to upload new versions of the data if needed (4TU.ResearchData allows for this) - so you're more in control of the output. 

And on IDR: perhaps it is worthwhile to just mention it in your Data Management Plan. Then you have this information somewhere findable. (Mentioning it in your plan does not oblige you to actually use the resource - it is a plan.)

**Comment by bertvanherck** [comment]
Hi Esther, 

Thank you for your reply, I'll add your suggestions to the plan. 

Regarding eLABjournal: I am using the TU Delft license.

**Comment by EstherPlomp** [comment]
Hi @bertvanherck: I can't seem to find a link to your readme file. If you'd still like feedback on this, can you please (re)share a link/file? Thank you!
