### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by EstherPlomp** [EstherPlomp/TNW-RDM-101#4]
Based on the [CookieCutter assignment](https://estherplomp.github.io/TNW-RDM-101/08-Realising-FAIR-Organisation.html#assignment-using-cookiecutter), or manual folder creation, please share your folder structure below:

**Comment by RamonvanValderen** [comment]
As general template I'll use the following folder structure:

├── .gitignore
├── CITATION.md
├── LICENSE.md
├── README.md
├── requirements.txt
├── 1-bin                   <- Compiled and external code, ignored by git (PG)
│   └── external            <- Any external source code, ignored by git (RO)
├── 2-config                <- Configuration files (HW)
├── 3-simulation_input      <- All input files to run a simulation, software specific
│   └── metadata            <- All metadata regarding simulation
├── 4-simulation_output     <- All raw data generated from simulation
├── 5-data_analysis_methods <- All files related to the analysis of the data, such as Python, Julia or Matlab files
├── 6-docs                  <- Documentation notebook for users (HW)
│   ├── manuscript          <- Manuscript source, e.g., LaTeX, Markdown, etc. (HW)
│   └── reports             <- Other project reports and notebooks (e.g. Jupyter, .Rmd) (HW)
├── 7-results
│   ├── figures             <- Figures for the manuscript or reports (PG)
│   └── output              <- Other output for the manuscript or reports (PG)
└── src                     <- Source code for this project (HW)

I've created my own Cookiecutter template and posted it on my Github account incase anyone is interested in using this as well: https://github.com/RamonvanValderen/cookiecutter-simulations. This template is setup specifically for projects where data is generated using multiphysics simulations (like computational fluid dynamics), which is subsequently post-processed and analyzed.
