### ISSUE TITLE
Assignment 1 Héctor Maldonado

### ISSUE THREAD

**Issue by Hctr95** [EstherPlomp/TNW-RDM-101#40]
### Introduction

Hello! I am Héctor Maldonado, a Ph.D. candidate in the Biotechnology Department from the AS Faculty. I come from Guatemala and like BBQs so much! 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the development of a framework to help in the designing and screening phases of bioreactor configurations. I am mostly interested in assessing the performance of the bioreactor configuration by considering hydrodynamic and mass transfer parameters (e.g., mixing times, volumetric mass transfer coefficients, and degree of homogeneity, among others).  This will allow the implementation of more detailed modeling strategies like CFD (Computational Fluid Dynamics) in the early phases of the bioreactor's selection. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Maybe  |
| Collaborate with industry  | Not in the immediate future, maybe at a later stage |
| Write/develop software as the main output of the project  | Yes |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

RDM should be considered more than a suggestion, it must be treated as a requirement to make research reproducible and accessible. It will avoid losing track of the progress of my codes, simulations, results, and data analyses. So far, I have noticed that my efforts to keep the data properly stored and documented save me some time, but there have been moments in which I lose quite some time looking for and solving some dependencies across files. In terms of horror stories, during a project from my master's, I was working with a team, and we decided to use Mendeley for keeping our library of references. On a Monday morning close to the deadline, the servers failed and we lost our library. Thankfully, I constantly made a copy of the papers and references in a local folder, this saved us and our work. 

### What would you like to learn during this course? 

I would appreciate learning about tools and tips to improve my DM skills, such that I can make sense of my previous work in the future and promote this practice among the students I will supervise and our research group. Ideally, I would like to get to know how to set up a collaborative environment for our research group that we can make use of for sharing scripts in a more effective way.  I aim to set my repository - finally - and be able to share it in the upcoming events I am planning to attend. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: [My_Data_Flow_Map](https://surfdrive.surf.nl/files/index.php/s/3VFtZvQMmf1vrHS)
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  [My_ImprovedData_Flow_Map](https://surfdrive.surf.nl/files/index.php/s/2O79AKPEYgChjSM)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @Hctr95! Thanks for handing in Assignment 2 and well done: it is very extensive and detailed! 

I only have a couple of suggestions/comments, and hopefully re-assurances: 

- Regarding your storage requirements: the project drive automatically extends up to 5 TB. After this you may need to confirm with our ICT manager (André van den Berg) that you would need more storage space, but in principle that request is always granted. Each project drive can be extended up to 100-200 TB, so I think you're more than covered! TU.ResearchData is also  free to use for TU Delft researchers up to 1 TB per researcher, per year. 
- Great work on your filenaming conventions! 
- Regarding visuals, Im not sure if it is helpful for your research but you may want to check out BioRender: [TU Delft has licenses](https://www.tudelft.nl/en/library/library-for-researchers/library-for-researchers/publishing-outreach/biorender) for this illustration software.
- You added a red flag for making your reduced-order models open source: Do you expect difficulties for this? Are the scripts you use (partially commercial?)

**Comment by Hctr95** [comment]
Hi @EstherPlomp. Herewith are my comments about your feedback: 

* Thanks for the heads up about the storage capacity.  Yes, it should be more than enough for the project. Thanks for sharing the contact from the ICT manager. 
* I already have a BioRender TUD-managed license. It is a game changer in terms of the quality and freedom when creating figures in the Biotech field. 
* I added the red flag due to the fact that if the developed workflow shows a great improvement over conventional approaches, it might be prone to be protected by IP rights. If that is the case, the usage of commercial software might be something to consider. _'Food for thought to keep up the motivation ;) and in mind'_

Hope this clarifies the assignment. 

Best,

**Comment by EstherPlomp** [comment]
Absolutely! Thanks for clarifying @Hctr95! And I'm happy to hear that you're happy with BioRender 😄

**Comment by Nasimhd** [comment]
You have a very detailed Readme file! I like how you provided all the required details.

I have different Readme files for different main folders in my project folder. This way there would be smaller files rather than one main file with many information.

**Comment by Nasimhd** [comment]
I like the idea of using Excel for data documentation and providing information about the data collected, variables, name conventions, descriptions and dependencies!

**Comment by EstherPlomp** [comment]
Thanks for sharing Assignment 3 and your readme file @Hctr95! Your assignment looks very comprehensive and detailed: well done! I don't have a lot of feedback, just some thoughts:

Documentation
- Interesting work by Shafi Arif et al. 2023! 
- Code versioning and dependency documentation is important indeed.

File formats
- While .csv files are indeed open, they do not preserve any formatting as you indicate. Whenever I share tabular data I tend to share both a .csv file and the .xlsx file: one I share because it is more user-friendly / has the file formatting, and the other I share to ensure that at least some of the information will be preserved for the long term. As long as you do not share TBs of data in different file formats, this is a great solution to both ensuring that your data is reusable and accessible!
- There is indeed a balance to sharing large data files: sharing the most relevant ones can be a great compromise to ensure that your research process is transparent and having enough space to share the underlying data of your research! 4TU.ResearchData should provide you with 1 TB per researcher, per year. This is hopefully enough for the most relevant data!

And thanks for sharing the HDF5/XML debate! Data management can indeed lead to interesting discussions and a one size fits all is generally difficult to find.

Regarding your very detailed and nice READme file: 
- If there are any questions that you do not find applicable/relevant, it is also fine to delete those and avoid cluttering of your READme file. 
- You can set up an ORCID for yourself! Register at https://orcid.org/. You can check [Cees Haringa's ORCID](https://orcid.org/0000-0003-0310-1045) to see an example of how this looks like when you have more research output.

**Comment by Hctr95** [comment]
Thanks for the feedback to both @EstherPlomp and @Nasimhd. 

I will take the suggestions into account for both the Readme file and the DMP. As a funny coincidence, I recently set up my ORCID which I found useful, and about the time to be shared for some work to be published soon.

**Comment by BiffoQ** [comment]
Hi Hector,

thanks for curating such a detailed Data Flow Map. In fact, I implemented a lot of things from your Flow Map in crating mine.

Cheers.
