### ISSUE TITLE
Assignment 1 Katja Garina

### ISSUE THREAD

**Issue by kgarina** [EstherPlomp/TNW-RDM-101#41]
### Introduction
Hi, I am Katja Garina and I am a second year PhD student at the Reactor Institute.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research is about food. More specifically, about meat alternatives. We are trying to understand how the plant-based meat alternative structure looks like on different length scales and how we can tune it, so that in the end we will have a meat-like texture.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Yes |
| Write/develop software as the main output of the project  | No |
| Use code (as in programming) for data analysis | Yes |
| Work with large data (images, simulation models) | Yes |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think the video demonstrates the importance of proper data storage very well. I also was surprised by how easily data can be manipulated and used incorrectly. So far, I don't have any horror stories and hope it will happen in the future. 

### What would you like to learn during this course? 

I work with large data obtained at different research facilities. In principle, I can always download my original data from them if my data is lost. However, data processing takes enormous amount of time. So, it would be nice  to organize proper storage of my processed data.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: [Data Flow Map 1](https://tud365-my.sharepoint.com/:p:/g/personal/kgarina_tudelft_nl/EfaxVNZNZQdPpevBspj1RWkBxByWSNDnhlx_aFbeP0wO4Q?e=33Qc2F) 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  [Data Flow Map 2](https://tud365-my.sharepoint.com/:p:/r/personal/kgarina_tudelft_nl/Documents/Desktop/TU%20Delft/TU%20Delft%EF%80%A8/courses/RDM/RDM101_Assignment2_Week2_DataFlowMap_Template.pptx?d=wdf25543d085347d9b7d251aa7505a951&csf=1&web=1&e=Janest)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by S-Aron** [comment]
Hi, I would consider to keep/create a backup on the Project Drive immediately after the measurements and not just having it on the SSD. Just in case.

**Comment by AnaSacristan** [comment]
Hi Katja,
I imagine that you will also be producing a lot of images from the data you collect (Spectra in the format of images for later publication and for your thesis). Perhaps you can consider this types of files as another category and also store it under the Project Drive as you create them.
🙂

**Comment by kgarina** [comment]
Here is my Readme file:
[Katja Garina_ReadmeTemplate.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/11602392/Katja.Garina_ReadmeTemplate.txt)

**Comment by EstherPlomp** [comment]
Hi @kgarina; Hereby your feedback for your readme file! It already looks very clear: well done!
 
- For the license/restrictions you can refer to your [preferred licence](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-6040138): CC-BY-SA. This places some requirements on the dataset: citation and if redistributed it should be under the same license. 
- It may be helpful to have some more description about what 'normal' conditions would look like. Is there a file that would describe this? Perhaps a methods section in a (future) article? 
- And very nice to see that you already have an ORCID!

**Comment by EstherPlomp** [comment]
Hi @kgarina - thanks for updating the link to assignment 3! Slowly we'll get through the OneDrive issues :) Everything looks very clear - well done! 

Metadata
-  Thanks for sharing that screenshot capturing your metadata, that makes it a lot clearer! Including the parameters sounds like a good idea 👍 

Access
- More of a question from my side: Do you find the Teams channel easy to use to collaborate/exchange data with others?

**Comment by lindaiqi** [comment]
Hi @kgarina , I read your Data Flow Map from assignment 2. It seems your data flow is organized chronologically. This is a good idea and it makes everything clear and reasonable. There are some abbreviation that could make layman confused.
