### ISSUE TITLE
Assignment 1 Jitske van Ede

### ISSUE THREAD

**Issue by jmvanede** [EstherPlomp/TNW-RDM-101#42]
### Introduction

Hi, my name is Jitske. I am doing my PhD at the faculty of Applied Sciences in the Environmental Biotechnology group and almost finished my first year. In my free time I really like to go rowing. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the the identification of an enzyme (a glycosyltransferase) which transfer so called nonulosonic acids (a specific type of sugars) onto the flagellin proteins of pathogenic bacteria. For this I will work a lot with mass spectrometry, and first aim to establish a metabolomics method to scan for these sugars in microbes, which will later be used as a substrate for the enzyme. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Maybe  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

The video clarifies the importance of data handling and storage very well. It shows the importance of storing your data, but also of having a proper documentation, making it easy to look back at your data and thereby allowing reproducibility. A worst nightmare would really be to lose all my data and thereby the work and time spend on it. So far I luckily do not have any horror stories. 

### What would you like to learn during this course? 

I am mostly working with mass spectrometry data, for which the raw data is automatically backed-up and therefore accessible. However, dataprocessing often consumes a lot of time and I would like to learn good ways on how to store and manage my processed data. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/pu2mw8XQOKr0nWK
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link: [JvE_RDM101_Assignment3_DataFlowMap_01.](https://surfdrive.surf.nl/files/index.php/s/pMN6AHUHlmplcLA)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by MPolinder** [comment]
Hey @jmvanede , your data flow map looks clear and complete to me. I have a minor suggestion: you could consider using OneNote for your lab journal. I used to keep a physical lab journal, which worked just fine, but using OneNote was a gamechanger for me. Linking multiple files to a protocol, being able to change and read notes whenever you have a PC with available, ordering different experiments by category, etc. It connects to the point @EstherPlomp made as well: you can keep online and offline copies of the notebook as a form of backup.

**Comment by EstherPlomp** [comment]
Thanks for sharing this @MPolinder!

**Comment by jmvanede** [comment]
Hi @EstherPlomp and @MPolinder, thank you both for the feedback! It is indeed a good point that I need to back-up my labnotes. I will look into OneNote as well.

**Comment by jmvanede** [comment]
This is the README file I created:
[JitskevanEde_NT_Sugars_README.txt](https://surfdrive.surf.nl/files/index.php/s/i8e8oVXUn7i07dU)

**Comment by EstherPlomp** [comment]
Thanks for sharing your assignment 3 @jmvanede! Well done: it is very comprehensive and clear! I only have a couple of thoughts/pointers:

Metadata
- Information about libraries/dependencies and their versions may be especially important for code to run properly

File formats
- MATLAB is indeed not an open file format. That doesn't necessarily mean that you need to convert it to Python. If you can indeed share as much as possible perhaps a re-user could do this themselves. As MATLAB is fairly widely used it is not a bad thing per-se that you're using this, it is just that Python is more accessible as it doesn't require licenses to use it. If you have a chance to start with Python this would be better, but you also shouldn't spend half of your PhD converting code :)

Data Publication
- I see some conflicting information in your answers here: on the one hand you state that you won't share the data in a repository but in the journal article itself, and on the other hand you're stating that you'll use 4TU.ResearchData and Metabolome Xchange. If you're sharing the data directly in the article it is fine to only share it in the article. Supplemental materials are not a good idea, however: these do not get a DOI (only the article itself!) and sharing data via supplemental materials do not follow the FAIR principles. As a PhD candidate of TU Delft you're expected to follow these FAIR principles, next to some of the other reasons that supplemental materials are [not a great way of sharing data](https://estherplomp.github.io/TNW-OS-support/posts/data-sharing-supplement/). 
- While GitHub is indeed a great place to share code, it doesn't actually allow you to assign a DOI to your repository. Here the integration with data repositories comes in, such as 4TU.ResearchData. When you share a snapshot of the repository on 4TU.ResearchData it will assign this DOI and also preserve your code for the long-term. GitHub is not a long-term storage solution as you can delete your repositories, or Microsoft could decide to do so whenever they feel like changing their terms of use. 

I hope this makes sense! If not, please also let me know :)

I'll get back about your READme file later!

**Comment by EstherPlomp** [comment]
And regarding your README: This looks great - well done! I only have some minor comments:

- For the license/restrictions you can refer to your [preferred license](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-5977233): CC-BY. While requiring citations is not a strict restriction, it technically is a restriction. 
- For external READme's it can be helpful to ORCID information. This is a persistent identifier for researchers. You can register for one here:  and you can have a look at [Martin's ORCID ](https://orcid.org/0000-0001-9897-0723) to see what this looks like when you have more research outputs. 
- Very nice methodological overview! Well done! If you want to share the methods more publicly you can also consider using [protocols.io](https://www.protocols.io/), which is a repository for protocols/methods.

**Comment by jmvanede** [comment]
Dear @EstherPlomp, Thank you for the feedback! I had a question regarding the part about Data Publication. I indeed stated that for some datasets I would use a repository, since it includes large raw data files, which cannot be published as it is. On the other hand, the HPLC chromatograms will most likely consist of one or a few figures which would be easier to publish in the article itself. But if I understand correctly, it would be best to store all the datasets on a repository such as 4TU.ResearchData?

**Comment by AnaSacristan** [comment]
Hi Jitske,

I read your Assignment 3 flow map and it looks very complete. I just have one suggestion regarding the lab notes. I'm still looking for the best option myself but I read about these 2 electronic lab notebooks which the TU Delft has subscriptions with. Here is the link, maybe it's worth it and avoid scanning all the notebook and have your notes in a more accessible way: https://www.tudelft.nl/en/library/research-data-management/r/manage/electronic-lab-notebook.

Let me know if you try any or OneNote and we can share experiences!

**Comment by kgarina** [comment]
Hi @jmvanede, I fully agree with Esther about your Assignment 3. It is very extensive and clear!

**Comment by EstherPlomp** [comment]
> Dear @EstherPlomp, Thank you for the feedback! I had a question regarding the part about Data Publication. I indeed stated that for some datasets I would use a repository, since it includes large raw data files, which cannot be published as it is. On the other hand, the HPLC chromatograms will most likely consist of one or a few figures which would be easier to publish in the article itself. But if I understand correctly, it would be best to store all the datasets on a repository such as 4TU.ResearchData?

Sorry @jmvanede: I missed this comment! 

Ideally this is indeed shared in a data repository - you can share additional files via the supplemental files in journals, but this has [several downsides](https://estherplomp.github.io/TNW-OS-support/posts/data-sharing-supplement/). If you only share figures and there is space for all of the figures in the article, then it is of course fine and you don't need to duplicate that information elsewhere. If you already have to share some data in the data repository anyway (for some of these raw data files) - it is hopefully not too much effort to add any additional figures/data. 

I hope this makes sense - if not, please also let me know!
