### ISSUE TITLE
Assignment 1 Daiqi Lin

### ISSUE THREAD

**Issue by lindaiqi** [EstherPlomp/TNW-RDM-101#46]
### Introduction

Hi all, this is Daiqi Lin. I'm studying in the Faculty of Applied Science. 
### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is about computational fluid dynamics and machine learning. Computational fluid dynamics package will be applied to simulate the blood flow in patient-specific geometry. Meanwhile, neural networks will be trained to predict flow field to cut computation time and expense.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes|
| Write/develop software as the main output of the project  | Yes  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

Bad management of data will definitely lead to research disaster. I always forget the details of data that I got several months ago. Then I need much time to recall the details. 
### What would you like to learn during this course? 

Good results should be transparent and reproducible. I will record how I get the data and document the data analysis.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). use password: 1111 Link: https://surfdrive.surf.nl/files/index.php/s/rQsY3uuu3FmdPwP 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/zYyv3FXFD7YOhKm
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @lindaiqi ! Thanks for handing in assignment 1! Could you please still add 2-3 sentences about what your research is about? Thanks!

**Comment by AngeliquePothuizen** [comment]
Feedback on Assignment 2: 
Hi! To me it feels like the basics are covered in your assignment but there is some room for elaboration. For example, how much data and what type of files to you expect to be generating?

**Comment by EstherPlomp** [comment]
Hi @lindaiqi! Thanks for following up with assignment 1 and for handing in assignment 2! 

It looks very clear, well done! I agree with @AngeliquePothuizen that more detail on the data type and format would be helpful: this also becomes more important for the next assignment! 

In terms of storage solutions, you may want to have a look at the [TU Delft instance of GitLab](https://gitlab.tudelft.nl), which is a safe solution for any scripts/codes of a more sensitive nature. You may also want to check out the workshops that the eScienceCenter is organising regularly: they often repeat workshops on a similar topic if you missed a particular one: https://www.esciencecenter.nl/events/?f=workshops

In the next assignment you'll also consider which part of your research can be publicly shared: this may be more complicated in your case with all the flags! @YiZhang025 and @JRdeJong also indicated working with personal data, so for the follow up assignment you may also want to have a look at each other's comments/solutions for this!

**Comment by EstherPlomp** [comment]
Hi @lindaiqi! Thanks for handing in assignment 3 - it looks clear! I have a couple of pointers:

Documentation/metadata
- With code it can also be very important to document versions and dependencies/libraries used. 

Data publication
- If the data/code is indeed confidential there may be sharing restrictions. Otherwise, [TU Delft does expect PhD candidates to share the code/data underlying the PhD projects](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary). 

Also: I see you marked that you shared your READme file above, but I don't see a link or a READme file in the comments. Can you please still share this? Thanks!

**Comment by RobinvanderHaar** [comment]
Hi @lindaiqi
Regarding data organization, I would recommend you to start the file names with the dates. This way, simulations are ordered chronologically. If you have some kind of log with which simulations you did when and what parameters you changed, you can easily find the corresponding files.

**Comment by YiZhang025** [comment]
Hi @lindaiqi,

Just noticed that you also work with MRI data and it seems you are also working on numpy. Your data flow map is inspiring to me as well, and it will be interesting to have a chat regarding the structure of folders, and also, how to store them in an efficient way.

**Comment by lindaiqi** [comment]
This readme file was generated on 2023-06-16 by Daiqi Lin


GENERAL INFORMATION

Title of Dataset: CFD simulation results of aorta 


Author/Principal Investigator Information
Name: Daiqi Lin
ORCID:0000-0001-8759-4937
Institution: TU Delft
Address: Van der Maasweg 9, 2629 HZ Delft
Email: d.l.lin@tudelft.nl

Author/Associate or Co-investigator Information
Name: Sasa
ORCID:
Institution: TU Delft
Address: Van der Maasweg 9, 2629 HZ Delft
Email: S.Kenjeres@tudelft.nl



Date of data collection: 2023-06-15
Geographic location of data collection: Delft, Netherlands

Information about funding sources that supported the collection of the data: None


SHARING/ACCESS INFORMATION

Licenses/restrictions placed on the data: no restriction

Links to publications that cite or use the data: N.A.

Links to other publicly accessible locations of the data: N.A.

Links/relationships to ancillary data sets: N.A.

Was data derived from another source? 
If yes, list source(s): 

Recommended citation for this dataset: Please note that the results of this dataset are caluclated from the MRI image of human aorta and boundary condition set up are also based on MRI measurement.


DATA & FILE OVERVIEW

File List: <list all files (or folders, as appropriate for dataset organization) contained in the dataset, with a brief description>
-case file: include all the parameters for model setup
-data file: include results
-journal file: record all the parameters to make calculation automatically
-udf file: user defined function
-script file: to run on the hpc

Relationship between files, if important: 

Additional related data collected that was not included in the current data package: None.

Are there multiple versions of the dataset?
If yes, name of file(s) that was updated: 
Why was the file updated? 
When was the file updated? 


METHODOLOGICAL INFORMATION

Description of methods used for collection/generation of data: <include links or references to publications or other documentation containing experimental design or protocols used in data collection>

Methods for processing the data: The dataset was calculated by CFD package Fluent. All the detailed parameter to build the numerical model was recorded by journal files.

Instrument- or software-specific information needed to interpret the data: Fluent 19.0 
Standards and calibration information, if appropriate: The simulation should be validated by MRI measurement.

Environmental/experimental conditions: 

Describe any quality-assurance procedures performed on the data: All the parameters should be recorded in journal file to make results reproducible.

People involved with sample collection, processing, analysis and/or submission: reproducible

**Comment by EstherPlomp** [comment]
Thanks for sharing your README @lindaiqi!

- I think your dataset title could be a bit more specific about either the content of the dataset or the research questions that this particular dataset is trying to address. It could also be data underlying a research publication, so then you could say: 'Dataset underlying the publication: [name publication]'. 
- Good to see that you already set up an ORCID! Sasa's ORCID is: https://orcid.org/0000-0002-7568-5513 (although it doesn't seemed to be used :))
-  For the 'Licenses/restrictions placed on the data' you can add [your preferred license from the licence thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-6035605). (CC BY-NC-SA4.0 and/or MIT)
- Not all of these questions will always be applicable to all of the datasets that you work with: you can also delete the questions that you do not find helpful. 
- I think your methodological information could be a bit more extensive - think about how you describe the methods in the method section of a publication. You can also copy/paste some of this information if that makes things easier. 
- Similar comment for the quality-assurance procedures: what are 'all the parameters'? 
- The last question is more aimed at anyone that supported the data analysis: did you do this all yourself or where there any technicians, students or colleagues involved?
