### ISSUE TITLE
Assignment 1 Jana Bauer

### ISSUE THREAD

**Issue by bauerjana** [EstherPlomp/TNW-RDM-101#47]
### Introduction

Hi all, I am Jana Bauer, a 1st year PhD student in the Department of Quantum Nanoscience. Originally, I come from Germany and I like everything that deals with music. 

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the quantum physical view of acoustics. I use nanoscale samples to investigate the properties of phonons in waveguides. Therefore, I spend a lot of time in the cleanroom to fabricate my samples which I then cool down to millikelvin for the quantum measurements. 

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |

### Reflections on the importance of RDM videos

A suitable data management and documentation are a crucial aspect of scientific working. However, I made some own experiences with bad data management as a Bachelor student. We got a simulation model (Simulink + Matlab code) from an industry partner to perform a parameter study - long story short: nothing worked, it was a mess, and there was literally zero documentation. In my opinion, many people are already aware of the necessity for a proper RDM, but still they struggle with the implementation - maybe because it is not part of BSc/MSc studies? 

### What would you like to learn during this course? 

No particular goals for this course. I would like to get started with good RDM techniques on a very practical approach. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/9DsbSFDByOZdhuo
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/poY5hyv6kedWYVK
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @bauerjana! Thanks for handing in your assignment 2! It looks great and very comprehensive!

Good to see the digital lab notes, as these are then also backed up! 

Following up from @dmuis comment: If you're still looking for a storage/sharing solution for your scripts/code, you may want to use GitHub or GitLab. GitLab is better to use if you're working with sensitive/commercial data and/or internal collaborators. GitHub is easier to work with external collaborators (but shouldn't be used for sensitive types of data/code)

**Comment by ArjanMejas** [comment]
Dear Jana, 

if I had to grade your Assignment 2, I would give it a "sehr gut"!

Best, 
Arjan

**Comment by EstherPlomp** [comment]
Hi @bauerjana! Thanks for handing in assignment 3! It looks very clear: well done! I therefore have little feedback: 

File formats
- CAD files such as .dxf are proprietary since you need CAD to open them. You could consider converting these to an open format such as .pdf/.svg - but this might result in too much loss of information/operability. See for similar considerations @MPolinder assignment 3 and [feedback,](https://github.com/EstherPlomp/TNW-RDM-101/issues/50#issuecomment-1576384469) and @francescozatelli assignment 3 and [feedback](https://github.com/EstherPlomp/TNW-RDM-101/issues/45#issuecomment-1577010438). 

Please do still share your readme file!

**Comment by bauerjana** [comment]
@EstherPlomp , thanks for the feedback regarding the assignment 3, especially the feedback considering the dxf files is very helpful! Generally, a conversion to pdf/svg should be possible. But since I never tried it so far, I'm also not sure about the loss of information. I might check that in the future. 

Also, here is my readme file: https://surfdrive.surf.nl/files/index.php/s/IaTLhKb636F7MPw .

**Comment by EstherPlomp** [comment]
Give it a try - and if it doesn't make any sense you can also forget about it again :) 

And thanks for sharing your READme! This looks very clear - great title as well! 
- If it is a dataset underlying the publication you may want to put that in front of the title, so: Dataset underlying the publication Al-made Manhattan Junctions sweeped in size and exposure dose on high-resistivity Si. 
- For external/public READme's ORCIDs are quite helpful. These are persistent/unique identifiers for you as a research and provide you with a place to gather your research outputs. You can [set up your own ORCID](https://orcid.org/register) or have a look at [Simon's ORCID](https://orcid.org/0000-0003-3932-7820) to see what it looks like once you have some more research outputs.

**Comment by ArjanMejas** [comment]
Dear @bauerjana, 

Assignment 3: Yet again, if I had to grade it, I would give it a "sehr gut"!

Readme.txt: Same comment as above.

**Comment by mausi122** [comment]
@bauerjana 
Some late (I was on a conference) feedback on your assignment 3

I think it looks good.
For your documentation of code aside from versioning good code comments and doc-strings are really important for code reuse. (I'm sure you're aware but I didn't spot it in the slides)

Also for the cleanroom recipes do you also have a kind of workflow/ protocol a new person in the group could follow or is it all in the format notes taken by people during the process? If the latter it might be nice to make such a protocol document before you leave.
