### ISSUE TITLE
Assignment 1 A. O. Biffo

### ISSUE THREAD

**Issue by BiffoQ** [EstherPlomp/TNW-RDM-101#49]
### Introduction
My name is Biffo. I am a PhD candidate at the Reactor Institute, Technical University of Delft. I love using the gym and playing football during my leisure.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
I am currently working the so-called Solid Oxide Fuel Cell system. This system is a renewable energy storage and conversion device. The goal of my PhD studies is to improve the performance of this device.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | Yes  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
To start with, I have no horror stories to share. And, the videos have enlightened me about the need to manage research data as this is pertinent for every research. 
### What would you like to learn during this course? 
Research Data Management

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://github.com/BiffoQ/RDM-Assignments/tree/master
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link: https://github.com/BiffoQ/RDM-Assignments/tree/master
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @BiffoQ! Thanks for handing in your assignment 2 - and on GitHub :) 

Well done on the assignment: it looks very detailed and comprehensive! 
- Indeed, visuals are also data! I'll repeat the same comment I also gave to Héctor, just in case it is of interest: Regarding visuals, Im not sure if it is helpful for your research but you may want to check out BioRender: [TU Delft has licenses](https://www.tudelft.nl/en/library/library-for-researchers/library-for-researchers/publishing-outreach/biorender) for this illustration software.
- I wonder what part of your data is personal data? You earlier indicated that you won't be working with it but in the assignment I see several personal data flags?
- Project/One Drive is an excellent combination :)

**Comment by RobinvanderHaar** [comment]
Hi Biffo,
I think you have a very good idea about the data you are generating. I like that you included visuals as well. Also think about collected literature and written texts (protocols, articles and other documents) as data you have to safeguard in some way.

I think you also have a very strong data security by working directly in an externally stored location. This way you won't lose anything in case something happens to your laptop or desktop.

**Comment by BiffoQ** [comment]
> Hi @BiffoQ! Thanks for handing in your assignment 2 - and on GitHub :)
> 
> Well done on the assignment: it looks very detailed and comprehensive!
> 
> * Indeed, visuals are also data! I'll repeat the same comment I also gave to Héctor, just in case it is of interest: Regarding visuals, Im not sure if it is helpful for your research but you may want to check out BioRender: [TU Delft has licenses](https://www.tudelft.nl/en/library/library-for-researchers/library-for-researchers/publishing-outreach/biorender) for this illustration software.
> * I wonder what part of your data is personal data? You earlier indicated that you won't be working with it but in the assignment I see several personal data flags?
> * Project/One Drive is an excellent combination :)

Thanks for the feedback, Esther. I have heard about BioRender, and I have been procrastinating checking it out. Maybe it is time to break the jinx. Thanks for mentioning it.

Regarding personal data, I could not find flags that reflect how I use my data. I thought 'personal' is the most relevant -- I might be wrong though.

Cheers :)

**Comment by BiffoQ** [comment]
> Hi Biffo, I think you have a very good idea about the data you are generating. I like that you included visuals as well. Also think about collected literature and written texts (protocols, articles and other documents) as data you have to safeguard in some way.
> 
> I think you also have a very strong data security by working directly in an externally stored location. This way you won't lose anything in case something happens to your laptop or desktop.

Thanks for your comment, Robin. In fact, you are right about collected pieces of literature and written texts. It is sad that they skipped my mind :(.  

Cheers :)

**Comment by EstherPlomp** [comment]
Thanks for responding @BiffoQ !

> 
> Regarding personal data, I could not find flags that reflect how I use my data. I thought 'personal' is the most relevant -- I might be wrong though.
> 

With personal data we mean data that can directly be traced back to an individual, such as a name, IP address, birth date etc. Do you have any of this data that allows you to identify an individual? 

Please also don't forget to provide feedback to other people's assignments!

**Comment by EstherPlomp** [comment]
Hi @BiffoQ! 

I don't see a file for your assignment 3 in the link that you included above, and I miss your READme file! Can you update the links and/or share it here as a new comment? 

Please also don't forget to provide feedback to other people's assignments, if you haven't already, and to add your data challenge and license preferences to the dicussion threads!

**Comment by EstherPlomp** [comment]
No worries @BiffoQ! I found them in the master branch indeed. You can also provide direct links to files in different branches. (for example, [your README](https://github.com/BiffoQ/RDM-Assignments/blob/master/AUTHOR_DATASET_ReadmeTemplate.txt)). I'm not sure why this happened, but can have a look at it if you want to get this fixed?

I'll have a look at the assignments later, for now some feedback on your README: 

README:
- I think your dataset title could be a bit more specific about either the content of the dataset or the research questions that this particular dataset is trying to address. It could also be data underlying a research publication, so then you could say: 'Dataset underlying the publication: [name publication]'.
- An ORCID is a persistent identifier for yourself as a researcher, and allows you to collect research outputs in one space that you can manage yourself. [You can set up your own ORCID](https://orcid.org/register), and have a look at [Pedro's ORCID](https://orcid.org/0000-0002-5246-6449) to see how it looks like when you have more research outputs.
- Is there any additional information that the Electroceramics Society wants you to add to research outputs? Or is just the name of the Society sufficient? 
- For the 'Licenses/restrictions placed on the data' you can add your preferred license from the [licence thread](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34). I don't think you completed this part yet, so please do still add your preferred licenses there! (See the [course materials for more information about licenses](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences).)
- Well done on adding the folder structure to the README!
- Your methodological information could be more comprehensive. For example: which different devices were used? If it is helpful you can also copy/paste and/or adjust information from the method section of a thesis chapter or publication, or directly refer to the publication for this information. 
- If any questions in the README template do not make sense for the data/software that you're working with, you can also delete those questions. That will make the file more readable.

**Comment by EstherPlomp** [comment]
And now your assignment 3 feedback! Thank you for handing this one in as well - it looks very clear - well done! Nice to see that you updated your assignment based on Héctor's assignment!

Some thoughts: 

**Data organisation**
- You shared your folder structure and naming, but not a file naming convention! See [The Turing Way](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-storage.html?highlight=file%20naming#file-naming-conventions) for some more info/guidance on this.

**File formats**
- Open file formats can help with the long term preservation of files, as some of the proprietary software cannot be opened by everyone, and might also not function any more in a couple of years. This is why it can helpful to share your files in an open file format, but only if this doesn't result in information loss. If your files aren't too large you can also consider sharing them in a proprietary/closed format, as well as the open format - so that you have the best of both!

**Licenses** 
- I noticed that you didn't share the license preferences in this assignment, the license thread and your README. Was the [course information](https://estherplomp.github.io/TNW-RDM-101/07-FAIR-principles.html#data-and-code-licences) not clear? Or do you need any help with this? I'm happy to sit down for a bit and go over your options! Let me know :)

**Comment by EstherPlomp** [comment]
And finally! I did not see feedback from you to people's assignment 2 and 3 and the README file: am I overlooking something? This is all I'm missing from your side to complete the course.

**Comment by BiffoQ** [comment]
Hi @EstherPlomp,

everything has been fixed.

Cheers.

Biffo.

**Comment by EstherPlomp** [comment]
Great, well done for completing all the course activities @BiffoQ! I noticed that in the post above you're quoting some text of mine: was there anything you wanted to respond to?
