### ISSUE TITLE
Assignment 1 Minco Polinder

### ISSUE THREAD

**Issue by MPolinder** [EstherPlomp/TNW-RDM-101#50]
### Introduction
Hi, I'm Minco, PhD candidate in the Cees Dekker lab (Bionanoscience).

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
My research focusses on chromosome dynamics during _prokaryotic_ cell division. By visualizing the dynamics of two mixed DNA constructs in a nanoconfinements, I want to learn about entropy-driven chromosome segregation.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos
The 'horror-stories' are of course exceptions and not daily reality. I do not have an experience like that myself, other than that I have wasted time on figuring out what the precise experimental conditions of certain datasets were since I did not properly link the data to my labjournal. Therefore, I realize that proper data management makes a project more structured and accessible, both for yourself and for others. The other advantages of proper data management that are discussed in the video/paper speak for themselves. 

### What would you like to learn during this course? 
I would like to get inspiration for setting up my own data management strategy for my own project.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: '[RDM101_DFM_1](https://tud365-my.sharepoint.com/:p:/g/personal/mpolinder_tudelft_nl/Ef0h-Gko48BMrfyOlzihVm8BWyjcWyXschDl63gJaqBs5g?e=nLFju3)'
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  '[RDM101_DFM_2](https://tud365-my.sharepoint.com/:p:/g/personal/mpolinder_tudelft_nl/EREwDZHXauFKu-SUKYdtJMUByP1hfVAXTugQj7ZN0A8dDQ?e=sZVs3q)'
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by jmvanede** [comment]
Hi Minco, I think you have a very nice and clear data flow map! It gives a good impression on the data you will create/collect and the size of it. You also seem to have an extensive infrastructure on where you will store your data.

**Comment by MPolinder** [comment]
Thank you @EstherPlomp and @jmvanede .

@EstherPlomp As far as I know our group does not really use the U: drive but the other drives with copies on local HDD's/PC's, I will ask around though!

**Comment by MPolinder** [comment]
I think many things in the template do not really apply to imaging data of an exploratory study (which is what I am doing predominantly).

[README.txt](https://github.com/EstherPlomp/TNW-RDM-101/files/11611100/README.txt)

**Comment by Banalikwu** [comment]
Hi Minco well done on the readme file. I have a only a few suggestions/questions:
You write that you have 5D .tiff-stacks (Wow 5D...) and I could imagine that it is hard to keep track of the order and how the stacks are ordered by dimensions. Do you have a way to keep track of that? Perhaps that is already part of the metadata, but that would depend on the microscope.
In your readme, you also write that you have custom-made microfluidic devices and I remember you telling us about different designs. Perhaps you can add to your data & file overview a way to keep track of designs and corresponding acquisitions.

**Comment by Banalikwu** [comment]
Hi Minco!

Some comments/suggestions on your data flow map:
You wrote that you will store some very important details of the autoCAD designs in the metadata (purpose, dimensions, fabrication details), I really like that! One thing in our group that is often missing is exactly this kind of information. So storing this in the metadata should really help out when others look through your stuff and potential next students on your project.
Perhaps a note on the data publication, specifically the code part: Do keep in mind that a lot of packages that you might be using have licenses of their own. This might impact your freedom in choosing licenses (something that I'm thinking of now and haven't considered for myself yet...) 
On the documentation of your code: If you want, we can have a talk about various options for code documentation. I already convinced you of switching to pycharm which helps you with docstrings (automatically generated lines of documentation for your functions/classes), but pycharm there is much more!
