### ISSUE TITLE
Assignment 1 Yi Zhang

### ISSUE THREAD

**Issue by YiZhang025** [EstherPlomp/TNW-RDM-101#52]
### Introduction

Hi! My name is Yi Zhang. I am a PhD student at medical imaging group at imaging physics. I also serve as a clarinet player.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research is to study the robustness and prior knowledge in deep learning models in medical image analysis. I am interested in using Bayesian statistics to estimate the uncertainty of the outputs of the deep learning models to evaluate them. Apart from the data, the knowledge also comes from the model we use, which has a natural preference for different tasks.
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | Maybe  |
| Write/develop software as the main output of the project  | Yes|
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

It's always true that even for a small group researchers, the transmission of results, codes, and data (properly) can be a big issue without a good RDM. For me, the nightmare was the version control for my own projects and collaboration as we were debugging and developing new features every day. Besides the code repository, the results for each version were also mixed up with a mess and it was hard to make conclusion based on these different versions of experiments.
### What would you like to learn during this course? 

It will be great to learn how to manage the data, code, and collaboration within the group. Also for my personal project, I want to make sure all experiments are safe and reproducible. I want to apply the experience during the course to my current project which has multiple versions and sensitive data.
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). [Link](https://surfdrive.surf.nl/files/index.php/s/2zalsmuwGUABZoE)  
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). [Link](https://surfdrive.surf.nl/files/index.php/s/v1GeULjnDpW6Ao0)
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @YiZhang025! Thanks for handing in your assignment 2!

Well done: It looks very comprehensive!

- Just a note on the use of GitHub: that is generally fine, unless you're also working with confidential code/software. In that case the [TU Delft instance of GitLab](https://gitlab.tudelft.nl) is a more secure storage solution. Even private repositories at GitHub are shared with Microsoft and TU Delft doesn't have a contract for this with Microsoft (like OneDrive/Office etc). 
- If you're making use of your local storage drive and the project drive: make sure you have a regular backup schedule set up. The data on your local drive are not backed up, unless they are also stored on OneDrive/SURFDrive. 
- Just to point out that the eSciencecenter is hosting a workshop on '[Image Processing with Python](https://www.esciencecenter.nl/event/image-processing-with-python/)' which may be relevant to you. If you can't make the workshop in June they do repeats of it every half year - ish!

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 and your READme file @YiZhang025! Your assigment 3 looks very clear - well done! Regarding data access/publication I do have some feedback for you below:

File formats
- Amazing that there's a script setup to convert the MATLAB files to Python/numpy! 
- Very nice to see that you save both the image file and the Python code!

Data Access/Publication
- The medical images you can indeed not share, unless permission has been obtained for this from research partners and the individuals to who the data belong. Your code may be a different story: if this is code developed as part of your PhD project, [TU Delft expects you to follow the FAIR principles](https://estherplomp.github.io/TNW-RDM-101/05-Essentials-for-Research-Data.html#policy-summary) and share the code publicly using a Data Repository such as 4TU.ResearchData or [Zenodo](https://zenodo.org/). There are [ways to integrate GitHub and Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) for example, that facilitate this public sharing of the code!

Regarding your READme file: 
- Great start! Some of these things are indeed difficult to fill out if there's no associated publication/actual dataset yet. 
- The template asks for two contacts in case one of you is not responding or has moved to a different institute after a project has ended. Normally collaborators and/or supervisors are listed here. 
- Great to see that you already have an ORCID!
- For the methodological section you can also copy the text from your paper's method section and refer to the paper indeed.

**Comment by lindaiqi** [comment]
@YiZhang025 Hey， I found that you also do some work to convert image into numpy. It seems that I will need to do similar work. If possible, can we have some further communication in this field?

**Comment by YiZhang025** [comment]
> @YiZhang025 Hey， I found that you also do some work to convert image into numpy. It seems that I will need to do similar work. If possible, can we have some further communication in this field?

Of course! We can either catch up in Teams or in-person after the session.

**Comment by r-huo** [comment]
Hi Yi! Very clear data flow map and storage strategy. One thing I could raise concern is whether the confidentiality of the results could be remained (is patient personal identifiable data erased in the analysis results?) and whether private cloud service you are using for backing up the medical images is reliable enough. 
The research topic is very interesting and meaning btw!

**Comment by r-huo** [comment]
Hi! I found your assignment 3 very inspiring, especially the themes regarding metadata and file formats because I also handle images and analysis scripts. It's indeed helpful to have a dedicated metadata file for the environment configuration and parameter set for reproducibility. The tools you mentioned at session 2 (Gitlens and hydra) are also useful!
