### ISSUE TITLE
Assignment 1 - Arjan Mejas

### ISSUE THREAD

**Issue by ArjanMejas** [EstherPlomp/TNW-RDM-101#55]
### Introduction

Hi, I‘m Arjan and I‘m a first year PhD student at QN.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

My research focuses on the mechanisms of electrical conductivity inside cable bacteria.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | No |

### Reflections on the importance of RDM videos

Since we‘re in 2023 and both advances in science and industry have given us the opportunity to back up data to any cloud based service with ease, it really is your fault if you don't do it. There are no horror stories of mine, all my data is backed up on at least one cloud based service and one or two hard drives.

### What would you like to learn during this course? 

I would like to get acquainted with new/better/different ways of data storage, beside those I‘m already familiar with.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://tud365-my.sharepoint.com/:p:/g/personal/amejas_tudelft_nl/EZTtYUL-ioJBoZQy6LIdcUoBRXOEZPwAHkDg6Equ6SEWXg?e=kaCWKw 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://tud365-my.sharepoint.com/:p:/g/personal/amejas_tudelft_nl/EcU6UYdmU81ClZQBTC_m3LIBVxDO7xTX00c1V3XS-PlAdg?e=5kituZ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @ArjanMejas! Thanks for handing in assignment 2: it looks very clear!

Since you're working with code/scripts, you may want to consider to version control these, using local git repositories or making use of platforms such as GitHub/GitLab. [GitLab](https://gitlab.tudelft.nl/) is ideal for projects that cannot be publicly shared and contain sensitive data/code. GitHub is better for working together with externals and having more visibility for your work.

And with 'in the cloud': do you mean project drive or OneDrive? Or are you making use of a different solution?

**Comment by ArjanMejas** [comment]
> Hi @ArjanMejas! Thanks for handing in assignment 2: it looks very clear!
> 
> Since you're working with code/scripts, you may want to consider to version control these, using local git repositories or making use of platforms such as GitHub/GitLab. [GitLab](https://gitlab.tudelft.nl/) is ideal for projects that cannot be publicly shared and contain sensitive data/code. GitHub is better for working together with externals and having more visibility for your work.
> 
> And with 'in the cloud': do you mean project drive or OneDrive? Or are you making use of a different solution?

Dear Esther, 

with 'in the cloud' I mean both.

Best, 
Arjan

**Comment by ArjanMejas** [comment]
> Hi @ArjanMejas,
> 
> I think you could also think about how you do the data analysis, I assume you use python or matlab for the analysis if that is the case you should also include how you store those so that you can reuse and reproduce any conclusions you reach.
> 
> Also it wasn't really part of this assignment but how do you organise the data you store? Can someone else use it without first having to spend a day trying to figure out what is what?

Dear Maurits, 

I‘m very confident to say that my data is very well organised and any other person would be able to understand it with ease.

Best, 
Arjan

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 3 @ArjanMejas! It looks great already, well done! I just have a couple of thoughts/pointers below:

Data organisation
- Organising things per research topic sounds like a great idea! 
- When you publish - do you also expect to share the MATLAB files/scripts?

Metadata
- I am not super familiar with MATLAB so this might be redundant, but do you perhaps also need information about the libraries/dependencies you're using?

File formats
- Excel and MATLAB files are not necessarily open formats: you'll need the programmes to interact fully with the files. Examples of open file formats would be .csv for .xls and Python instead of MATLAB. 

Publication
- The default license of 4TU.ResearchData is indeed CC0. You mentioned CC BY-SA and MIT in [your answer ](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34#discussioncomment-6030460), which is what you can focus on when you answer this question in your Data Management Plan!

**Comment by dmuis** [comment]
Hi @ArjanMejas , your assignment 3 looks good. I think it is nice that your data comes in open source format and you plan to use the CC-0 license on 4TU.ResearchData.
Maybe one comment to think about: You said you organize your folders according to topic, but to me it sounds that the same measurements on field and temperature will come back over and over again during your PhD. Thus it will be handy to provide them with metadata with e.g. date and collaborators, to keep them separated over the years :) Good luck with your project!

**Comment by ArjanMejas** [comment]
Here is my Readme.txt file: https://tud365-my.sharepoint.com/:t:/g/personal/amejas_tudelft_nl/ET906H0OUH9Moy09qLULMCEBZQAg2Rcv26FerNjyAATtsg?e=CdylxD

**Comment by RobinvanderHaar** [comment]
Hi @ArjanMejas,
I like your README file, it is short and to the point and seems to contain all the information necessary for people to understand your work.

**Comment by EstherPlomp** [comment]
Hi @ArjanMejas! I can't seem to access your READme file: Can you reshare the link? Thank you!

**Comment by ArjanMejas** [comment]
Dear @EstherPlomp, 

here is the link to my Readme file: https://tud365-my.sharepoint.com/:t:/g/personal/amejas_tudelft_nl/EXFbirlX7MBLqWYOa3Lnm0YBYWyDA2IPJoioIvuGoIVCbg?e=Yx0LdI

**Comment by EstherPlomp** [comment]
Thanks @ArjanMejas! Your READme looks clear!

Some suggestions:
- You can consider [setting up an ORCID for yourself](https://orcid.org/register) - this is a nice way of gathering your research outputs in one place
- Does your funder require you to cite a certain funding/project number in acknowledgements? In that case it is good to add that information into the READme as well!
- For methodological information you can later on refer to the accompanying publication and/or copypaste some of the method information from there into your READme file. This depends on what makes the most sense for you/the dataset.
