### ISSUE TITLE
Assignment 1 Djanick de Jong

### ISSUE THREAD

**Issue by DjanickdeJong** [EstherPlomp/TNW-RDM-101#56]
### Introduction
Hi all, my name is Djanick de Jong and  I am a 1st year PhD student at the department of BioNanoscience.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)
I am working on algae-based living materials. My research aims to use the motion of algae to induce actuation in the material.
For this, we use (porous) hydrogels and microscopic techniques.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | Yes  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I think the video convinced me that it is important to manage research data. Especially, if you can not backtrack your data about what you have been doing for the last years, seems to me like a terrible feeling. Especially if a lot of time and effort has been put into the research project.  Apart from that, I do agree that transparency is crucial in science, for reproducibility of the experiments. The more details, and easier you can make it for others to control your data (or data analysis), the stronger the science and truth.  

### What would you like to learn during this course? 

Structurally ordering my data, I want to find files as easily as possible even after 4 years. Either by a template or program that could do this. 

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/oV1ZdqzgZEqFexM 
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/h5WkVeGRUgO5A5l
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [x] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by moengels** [comment]
Hi Djanick, I really like your Data Flow Map, very detailed and even separated into different instruments and their requirements. In addition, the considerations about file naming in storage are good. Did you consider using version control for your image analysis scripts? I benefited quite a lot from it and it's I guess also relevant for publishing to provide the code for the analysis.

**Comment by EstherPlomp** [comment]
Hi @DjanickdeJong! Thanks for handing in your assignment 2!

Your assignment already looks very detailed/extensive, so I only have a couple of comments:
- I like your flags for reproducibility/consistency in data analyses!
- Following up from @moengels great comment on version control: you can also use GitHub/[GitLab](https://gitlab.tudelft.nl) to manage your software/scripts. 
- As also mentioned to @Banalikwu and @YiZhang025 who are also working with images/Python: the eScience Center organises a workshop on '[Image Processing with Python](https://www.esciencecenter.nl/event/image-processing-with-python/)' every now and then, which might be of interest to you.
- You might want to have a look at [OneDrive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#onedrive) as well - this is a bit more user-friendly than the university drives and still provides you with 1 TB of space. 

Well done!

**Comment by EstherPlomp** [comment]
Hi @DjanickdeJong - thanks for handing in assignment 3! It looks very comprehensive and clear: well done! I therefore only have very little feedback:

Documentation: 
- When you share the data/code via a repository that uses the DataCite metadata standard (such as 4TU.[ResearchData](https://data.4tu.nl/) and [Zenodo](https://zenodo.org/)) you'll indeed automatically also provide this information: well spotted!

Access: 
- You can also make use of [SURFfile sender](https://filesender.surf.nl/) to send over large files to collaborators (your collaborators can also do this themselves if they are working at a Dutch institute). The receiver does not need a SURF account - only the sender does!

**Comment by DjanickdeJong** [comment]
This readme file was generated on 2023-06-09 by Djanick de Jong

GENERAL INFORMATION

Title of Dataset: Algae [strain] in [type] hydrogel

Aim experiment: With this experiment, we want to visualize the inner structures of the hydrogel and the motion of algae. Previously, we tested property x, and we changed property y this time to observe a significant change. 

Author/Principal Investigator Information
Name: Djanick de Jong
ORCID: https://orcid.org/0000-0002-2936-9317
Institution: Delft University Applied Sciences
Address: Maasweg 9 Delft
Email: W.J.deJong@tudelft.nl

Author/Associate or Co-investigator Information
Name: Marie-Eve Aubin-Tam
ORCID: https://orcid.org/0000-0001-9995-2623
Institution: Delft University Applied Sciences
Address: Maasweg 9 Delft
Email: m.e.aubin-tam@tudelft.nl


Date of data collection: 2023-06-09 at 12:05 

Geographic location of data collection: Delft, Applied Sciences, Netherlands

Information about funding sources that supported the collection of the data: 
ERC grant (not sure about the code, I will check)


SHARING/ACCESS INFORMATION

Licenses/restrictions placed on the data: 
CC-BY-4.0


Recommended citation for this dataset: 

Srikkanth Balasubramanian et al. “Bioprinting of Regenerative Photosynthetic Living Materials”.
In: Advanced Functional Materials 31.31 (2021), p. 2011162. DOI: 10.1002/adfm.202011162


DATA & FILE OVERVIEW

File List: Name.Data.1, Name.Date.2, ... [Each folder is a separate experiment]

Relationship between files, if important: 

You can do multiple types of Imaging with the same sample [e.g., FRAP, large image, resonant, z-stack]

Additional related data collected that was not included in the current data package: 



METHODOLOGICAL INFORMATION

Description of methods used for collection/generation of data: 
-based on methods paper x from literature.
-Main protocols on our local storage, linked with the readme files. In the end the detailed main protocols will be open acces. 


Details: 

concentrations building blocks hydrogel, type of experiment (FRAP, Phototaxis, Interaction studies), cell information (age, density).


Methods for processing the data: 
ImageJ and Matlab. A detailed description of the code will be placed in an online respirator, e.g. GitHub Zenodo.


Instrument- or software-specific information needed to interpret the data: include full name and version of software, and any necessary packages or libraries needed to run scripts

-ImageJ.2.9.0
-MATLAB 2020a (I will note if any additional packages needs to be downloaded for proper functioning)


Standards and calibration information, if appropriate: 
Laser intensity calibration, check the power of the laser power onto the sample.


Environmental/experimental conditions: 
Room temperature, and humidity levels.
Sample contains 2 drops of 80 microliters to prevent evaporation

Describe any quality-assurance procedures performed on the data: 
this will be in the form of experimental controls.

People involved with sample collection, processing, analysis, and/or submission: 
Only I and my BSc student

Number of variables: 
see Metadata, most important: Imaging speeds, pixel resolution in xy and z, and laser power.

**Comment by PabloVelazquezGarcia** [comment]
Hi Djanick,
Regarding assignement 2, very nice workflow map!
Did you consider storing your data in some additional place (hard drive, different drive...)? I guess you are generating very heavy data for doing that easily.
I would also like to ask, how do you manage to arrange these ammounts of data when you have to supervise students? It must be difficult to show them how to properly store all the data without creating a big mess!

**Comment by EstherPlomp** [comment]
Hi @DjanickdeJong - thanks for sharing your READme file - it looks very clear and comprehensive!

- I like how you use placeholders in the title, very clear! Its also nice to have the aim explained in the beginning, this makes it easier for people to decide if they want to continue reading and using the data. 
- Nice to see that you already have an ORCID!
- Please indeed check if the ERC wants you to refer to any specific (project)numbers. 
- Is the recommended citation the accompanying paper of the dataset? It can be helpful to add 'Please cite the accompanying publication' in this case

**Comment by DjanickdeJong** [comment]
@PabloVelazquezGarcia  _ All raw data is stored on the M drive in the Student's Folder. It is useful to validate if the naming makes sense from time to time. 

For the other question, my hope is that the backups of the M drive of TUDelft are sufficient, but indeed I could also buy some physical storage disks just in case anything goes wrong (better safe than sorry). Thanks for the tip.

Best,
Djanick

**Comment by DjanickdeJong** [comment]
@EstherPlomp  Thanks!

**Comment by EstherPlomp** [comment]
> 
> For the other question, my hope is that the backups of the M drive of TUDelft are sufficient, but indeed I could also buy some physical storage disks just in case anything goes wrong (better safe than sorry). Thanks for the tip.
> 

Just to stress that the [project drive](https://estherplomp.github.io/TNW-OS-support/posts/storage-solutions/#project-drive) should definitely provide you with enough storage space, and it is also automatically backed up (which physical storage disks are not). You can initially store up to 5 TB and this can be extended afterwards if needed!

**Comment by r-huo** [comment]
Hi Djanick! Thanks for sharing your readme file, which is clear and informative. I wonder if the images you acquire, at the commercial setups at BN with established softwares I assume, have auto-saved metadata with each image? Because usually they do and it could be really helpful to e.g. check the laser intensity.
