### ISSUE TITLE
Assignment 1 Pablo Velazquez

### ISSUE THREAD

**Issue by PabloVelazquezGarcia** [EstherPlomp/TNW-RDM-101#57]
### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | Yes/No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes/No  |
| Collaborate with industry  | Yes/No  |
| Write/develop software as the main output of the project  | Yes/No  |
| Use code (as in programming) for data analysis | Yes/No  |
| Work with large data (images, simulation models) | Yes/No  |
| Other:  | N/A  |
### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [ ] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [ ] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: 
- [ ] Provide feedback to at least one Assignment 2 from another participant
- [ ] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [ ] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [ ] Respond to **this** GitHub issue with your readme file
- [ ] Provide feedback to at least one readme file from another participant
- [ ] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  
- [ ] Provide feedback to at least one Assignment 3 from another participant
- [ ] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [ ] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @PabloVelazquezGarcia ! Can you please still answer the questions in the assignment? Thank you!
