### ISSUE TITLE
Assignment 1 Ana Sacristan

### ISSUE THREAD

**Issue by AnaSacristan** [EstherPlomp/TNW-RDM-101#59]
### Introduction

Hi everyone, my name is Ana Sacristan. I am a PhD candidate at the Radiation Science and Technology Department. I started last October.

### Describe your research in 2-3 sentences to someone that is not from your field (please avoid abbreviations)

I am studying the corrosion behavior of different alloys and ceramics exposed to molten salts. This research is aimed at understanding the corrosion damage of molten salt nuclear reactor’s structural materials.

### My research entails the following aspects: 

| Research Aspect | Answer |
| ------------- | ------------- |
| Use/collect personal data (health data, interviews, surveys)  | No  |
| Use/collect experimental data (lab experiments, measurements with instruments)  | Yes  |
| Collaborate with industry  | No  |
| Write/develop software as the main output of the project  | No  |
| Use code (as in programming) for data analysis | No  |
| Work with large data (images, simulation models) | Yes  |
| Other:  | N/A  |
### Reflections on the importance of RDM videos

I agree with the fact that reproducibility is a fundamental part of science and that the analysis of data can lead to errors so if more people can look at it and trace back what your steps were to reach that conclusion, less errors are going to be made. It is also good to have documentation for future-self and others to continue and build-up the research. Fortunately I don’t have any horror stories and hopefully I can avoid them with this course.

### What would you like to learn during this course? 

I would like to have a controlled way to store my data, which is ordered and easily accessible. I would like to learn how to deal with data and feel confident that it won’t be lost.

### Checklist assignments 

- [x] Assignment 1: creating a GitHub issue (before **Class 1**)
- [x] Respond to the GitHub issue on '[data challenge](https://github.com/EstherPlomp/TNW-RDM-101/discussions/33)'
- [x] [Assignment 2](https://estherplomp.github.io/TNW-RDM-101/06-Assignment-Data-Flow-Map-1.html): Data Flow Map 1 (share a link in this issue before **17 May 13:00**). Link: https://surfdrive.surf.nl/files/index.php/s/orNTqEiqrWytsNr
- [x] Provide feedback to at least one Assignment 2 from another participant
- [x] Respond to the GitHub discussion on '[licenses](https://github.com/EstherPlomp/TNW-RDM-101/discussions/34)'
- [x] Respond to the GitHub discussion on '[folder structure](https://github.com/EstherPlomp/TNW-RDM-101/discussions/36)'
- [x] Respond to **this** GitHub issue with your readme file
- [x] Provide feedback to at least one readme file from another participant
- [x] [Assignment 3](https://estherplomp.github.io/TNW-RDM-101/11-Assignment-Data-Flow-Map-2.html): Data Flow Map 2 (share a link in this issue before **31 May 13:00**). Link:  https://surfdrive.surf.nl/files/index.php/s/mMZLCG7wngko9CJ
- [x] Provide feedback to at least one Assignment 3 from another participant
- [x] [Assignment 4](https://estherplomp.github.io/TNW-RDM-101/13-Assignment-DMP.html): Data Management Plan (before **Class 2**)
- [ ] Respond to the GitHub discussion on '[Data Management Plans](https://github.com/EstherPlomp/TNW-RDM-101/discussions/35)' if you have any questions (optional)
- [x] [Assignment 5](https://estherplomp.github.io/TNW-RDM-101/14-Assignment-Data-Flow-Map-3.html): Data Flow Map 3: submit your slide (before **Class 2**)

**Comment by EstherPlomp** [comment]
Hi @AnaSacristan! thanks for sharing your assignment 2! 

It already looks very comprehensive: well done! I only have a couple of thoughts: 
- I havent seen Notion/Miro being used as a labnotebook so I'd be curious to hear about your experiences! @MPolinder also [mentioned using OneNote](https://github.com/EstherPlomp/TNW-RDM-101/issues/42#issuecomment-1556857445) for this purpose, so that might also be an alternative if this option doesn't work for you.
- I see you're not using code for the image analysis whereas a couple of other PhDs were using Python for image analysis. Pending on how comfortable you are with programming it might be something to consider? 
- And just a note that your articles/literature/chapters should also be stored somewhere: will you use the same solutions?

**Comment by Banalikwu** [comment]
Hi @AnaSacristan, 

For the photographs of various magnifications before/after exposure, what is your system for naming the different files and experiments? I typically include a lot of identifying details in my filenames, including date, experiment number of the day, concentration of important chemicals, etc. Next to that, all of those details are of course saved in my lab notes, but I find that such as system helps me to identify relevant files quickly without the need to cross-check my notes.

For the simulated phase diagrams, do what data is stored there? Do you also store the input parameters next to your data?

For the data that is stored on the computers of the instruments, do you ever have the need to delete some of those files? In my lab these computers quickly fill up with lots of data and we occasionally have to delete older files to free up space for new experiments. I suppose that for you, your backups are sufficient, but I'm curious if you have a specific system for deleting stuff :)

**Comment by AnaSacristan** [comment]
Hi @EstherPlomp,
Thanks for your comments. I have been using Notion to organize my project and literature review and I recently saw a template of a Lab notebook, with one page for Lab Protocols, one for planned activities and others to write experimental conditions similar to a journal. I guess I will try that one or look at OneNote as MPolinder suggested. I was wondering if Miro was a good idea but perhaps the other two programs are better suited.
I'm not using code for the image analysis yet but I am learning Python and I do want to use it, I think it would make everything easier and more reproducible. Also to make plots, and I had a course last week (Software Carpentry Workshop from the Graduate School) where they showed how to save the code in GitHub so I think I'll do that.
As for the literature research I'm also saving everything in U: Drive, taking notes in Notion and I will start using some program as Mendeley to help with bibliography when writing.

**Comment by AnaSacristan** [comment]
Hi @Banalikwu,
Thank you for your feedback, It is in deed a very good practice to include information in the name of the files. What I typically include in the photographs is the date, the sample, if it is after/before exposure and the magnification as it helps me to compare the images before/after exposure with the same magnification and to be able to open them quickly. After that I include a number if I have more than one picture with the same magnification. I hope this information will be enough, otherwise as you say, I 'll have my notes.
For the phase diagrams, right now I have an Excel file with all of the parameters and the references where I found them in literature or the ones I have tried. It has worked for now. Do you have any other suggestions?
For the data stored in the computers of the instruments I have never encountered that it is erased but that is a good point to check. I am now using a microscope and I found my Masters folder (from 2016) still there with all of my images. It actually surprised me so I will ask the people in charge of the instruments about this. Thanks, it is a good point to know.

**Comment by AnaSacristan** [comment]
Here is my README file: https://surfdrive.surf.nl/files/index.php/s/ePE8Pe0JlegOJmH

**Comment by EstherPlomp** [comment]
Thanks for responding @AnaSacristan, and for sharing your READme file and assignment 3!

Regarding to your response to feedback from **Assignment 2**:
- Miro could also work as a labnote journal - I was just wondering because I have never tried this myself and haven't seen examples yet! The most important thing is to find a solution that works for you - which may indeed take some testing :)
- Well done on following the Software Carpentry Workshop! 
- The Umbrella/project drive can indeed be used for all types of research data. I feel obliged to also point out an open source alternative to mendeley: [Zotero](https://www.zotero.org/) (it also has a word/google doc integration and the export capacities are better compared to Mendeley). 

Regarding **Assignment 3**: Well done again - this is super extensive and comprehensive so I have very little to add! 👍 
File formats:
- It should be possible to export information from RSpace and eLABJournal to file formats of your preference, including .txt files. But it is safer to test this indeed :)

And I'll get back to you about the READme file later!

**Comment by S-Aron** [comment]
Great Data Management Plan @AnaSacristan. I looked through of it but I did not find a part where I would extra advice. Congrat!

**Comment by EstherPlomp** [comment]
And the feedback for your README: Well done: this already looks very clear!

- For the title: try to be a bit more descriptive - what research question is this data trying to address? Is it a dataset underlying a publication? In that case the title can also be 'Dataset underlying the article [title article]'
- ORCIDs are persistent identifiers for researchers! You can set up your own here: https://orcid.org/register and you can have a look at [Anna's ORCID](https://orcid.org/0000-0002-0355-5859) to see how it looks like when you have more research outputs. 
- For the license/restrictions you can refer to your dataset license preference: CC-BY. That is not a strict restriction, as it only requires citation, but that is still technically a restriction. 
- Do you not have any quality measures when you collect data? Any calibrations that take place? Particular settings that you always need to follow or monitor?

**Comment by MPolinder** [comment]
Hi @AnaSacristan , I think your README file looks indeed clear. However, aside from the title that could be more descriptive, I would also suggest to add more information to the methodology. That way someone might understand better what he is looking at when going through the data:)
