### ISSUE TITLE
Assignment 2 Hua Chen

### ISSUE THREAD

**Issue by HuaChenTUDelft** [EstherPlomp/TNW-RDM-101#93]
Hi all,

Below is my data flow map. Feel free to comment on it.

[RDM101_Assignment2_Week1_DataFlowMap_Hua Chen.pptx](https://github.com/EstherPlomp/TNW-RDM-101/files/12665044/RDM101_Assignment2_Week1_DataFlowMap_Hua.Chen.pptx)

Best,
Hua

**Comment by EstherPlomp** [comment]
Thanks for handing in assignment 2 @HuaChenTUDelft! I'll move the link to your assignment to your first issue, just so that I have a better overview of all the assignments and links :)
