### ISSUE TITLE
Assignment 2 - Federico Ramirez Gomez

### ISSUE THREAD

**Issue by federa7** [EstherPlomp/TNW-RDM-101#95]
Hello everyone,

I share with you the link to my [assignment 2](https://surfdrive.surf.nl/files/index.php/s/nfc0nBOW3Ly8T14). I hope it is clear for everyone. In my case, I couldn't think of particular flags for the type of data I will be working on.

Let me know if you identify any point of improvement or if you have any comment. 

Best,
Federico

**Comment by EstherPlomp** [comment]
Thanks for handing in the second assignment @federa7! I'll move the link to your earlier assignment #79 so that it will be easier for me to keep track of things :)
