### ISSUE TITLE
Assignment 2 - Pietro Sillano

### ISSUE THREAD

**Issue by pietro-sillano** [EstherPlomp/TNW-RDM-101#96]
Hello everyone,

I share with you my data flowmap: [file](https://docs.google.com/presentation/d/1RoC9I9dmw_XLwUOf9k2qkhAUGlZhOrSYzveds7aTGa0/edit?usp=sharing)
Feel free to share any improvements or comments on it. Thank you!
Best,
Pietro

**Comment by EstherPlomp** [comment]
Hi @pietro-sillano! Thanks for handing in assignment 2! I'll move your comment/link to the first issue just so that I have a better overview of all the assignments and links :)
