### ISSUE TITLE
Assignment 2 Yutong Wang

### ISSUE THREAD

**Issue by Upsiton** [EstherPlomp/TNW-RDM-101#99]
Hey, here is my data flow map: https://surfdrive.surf.nl/files/index.php/s/Aptf7EO7tjqqje5
Please feel free to give me any feedback. Thanks!

Best,
Yutong

**Comment by EstherPlomp** [comment]
Thanks for sharing assignment 2 @Upsiton! I'll move the link to your first assignment #85, just so that I have a better overview of all the links and assignments!
